# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      build:
        docker:
          - image: pandoc/latex

        steps:
          - checkout

          - run:
              name: Setup dependencies
              command:
                apk add make texlive-xetex ttf-dejavu

          - run:
              name: Build all formats
              command:
                make all

          - run:
              name: Check if epub exists
              command:
                test -s build/epub/book.epub

          - run:
              name: Check if html exists
              command:
                test -s build/html/book.html &&
                test -s build/html/style.css &&
                test -s build/html/images/cover.png &&
                test -s build/html/images/seagull.png

          - run:
              name: Check if pdf exists
              command:
                test -s build/pdf/book.pdf

          - run:
              name: Check if docx exists
              command:
                test -s build/docx/book.docx